kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: myapp
  namespace: myns
  labels:
    name: myapp

spec:
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 10
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: myapp