---
kind: ServiceAccount
apiVersion: v1

metadata:
  name: tiller-sa-myns
  namespace: myns

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: tiller-sa-crb-myns
  namespace: myns

subjects:
  - kind: ServiceAccount
    name: tiller-sa-myns
    namespace: myns

roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
